apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saleor-api
  template:
    metadata:
      labels:
        app: saleor-api
    spec:
      containers:
        - name: saleor-api
          image: ghcr.io/saleor/saleor:3.20
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: saleor-config
          volumeMounts:
            - name: saleor-media
              mountPath: /app/media
      volumes:
        - name: saleor-media
          persistentVolumeClaim:
            claimName: saleor-media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: saleor-api
spec:
  selector:
    app: saleor-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saleor-dashboard
  template:
    metadata:
      labels:
        app: saleor-dashboard
    spec:
      containers:
        - name: saleor-dashboard
          image: ghcr.io/saleor/saleor-dashboard:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: saleor-dashboard
spec:
  selector:
    app: saleor-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "saleor"
            - name: POSTGRES_PASSWORD
              value: "saleor"
          volumeMounts:
            - name: saleor-db
              mountPath: /var/lib/postgresql/data
            - name: init-db
              mountPath: /docker-entrypoint-initdb.d/replica_user.sql
      volumes:
        - name: saleor-db
          persistentVolumeClaim:
            claimName: saleor-db-pvc
        - name: init-db
          configMap:
            name: init-sql
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.0-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: saleor-redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
            - containerPort: 16686
            - containerPort: 14268
            - containerPort: 9411
          volumeMounts:
            - name: jaeger-tmp
              mountPath: /tmp
      volumes:
        - name: jaeger-tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - name: udp-sampling
      protocol: UDP
      port: 5775
      targetPort: 5775
    - name: udp-collector
      protocol: UDP
      port: 6831
      targetPort: 6831
    - name: udp-agent
      protocol: UDP
      port: 6832
      targetPort: 6832
    - name: tcp-config
      protocol: TCP
      port: 5778
      targetPort: 5778
    - name: http-query
      protocol: TCP
      port: 16686
      targetPort: 16686
    - name: http-collector
      protocol: TCP
      port: 14268
      targetPort: 14268
    - name: zipkin
      protocol: TCP
      port: 9411
      targetPort: 9411
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
        - name: mailpit
          image: axllent/mailpit
          ports:
            - containerPort: 1025
            - containerPort: 8025
---
apiVersion: v1
kind: Service
metadata:
  name: mailpit
spec:
  selector:
    app: mailpit
  ports:
    - protocol: TCP
      port: 1025
      targetPort: 1025
    - protocol: TCP
      port: 8025
      targetPort: 8025
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saleor-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saleor-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saleor-media-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: saleor-config
data:
  JAEGER_AGENT_HOST: "jaeger"
  DASHBOARD_URL: "http://localhost:9000/"
  ALLOWED_HOSTS: "localhost,api"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql
data:
  replica_user.sql: |
    -- SQL script for database initialization
    CREATE ROLE replica_user WITH LOGIN PASSWORD 'replica_password';

