---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saleor-api
  template:
    metadata:
      labels:
        app: saleor-api
    spec:
      containers:
      - name: saleor-api
        image: ghcr.io/saleor/saleor:3.20
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgres://saleor:saleor@postgres-service:5432/saleor"
        - name: REDIS_URL
          value: "redis://redis-service:6379/0"
        - name: JAEGER_AGENT_HOST
          value: "jaeger"
        - name: DASHBOARD_URL
          value: "http://saleor-dashboard-service/"
        - name: ALLOWED_HOSTS
          value: "localhost,api,104.197.234.205"
        volumeMounts:
        - name: saleor-media
          mountPath: /app/media
        resources:
          limits:
            cpu: "2"
            memory: "512Mi"
          requests:
            cpu: "1"
            memory: "400Mi"
      volumes:
      - name: saleor-media
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: saleor-api-service
spec:
  selector:
    app: saleor-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort

