---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saleor-worker
  template:
    metadata:
      labels:
        app: saleor-worker
    spec:
      containers:
      - name: saleor-worker
        image: gcr.io/isec6000-434507/saleor:latest
        command: ["celery", "-A", "saleor", "--app=saleor.celeryconf:app", "worker", "--loglevel=info", "-B"]
        env:
        - name: DATABASE_URL
          value: "postgres://saleor:saleor@postgres-service:5432/saleor"
        - name: REDIS_URL
          value: "redis://redis-service:6379/0"
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        volumeMounts:
        - name: saleor-media
          mountPath: /app/media
      volumes:
      - name: saleor-media

